// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab.API.Swagger.Models;

public partial class Log
{
    public int Id { get; set; }

    public string Message { get; set; }

    public string Level { get; set; }

    public DateTime? TimeStamp { get; set; }

    public string Exception { get; set; }

    public string Properties { get; set; }

    public string SourceContext { get; set; }

    public string Title { get; set; }

    public int? Status { get; set; }

    public string Detail { get; set; }

    public string Instance { get; set; }

    public string TraceId { get; set; }

    public string ControllerName { get; set; }

    public string ActionName { get; set; }
}