// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab.API.Dapper.Models;

public partial class Book
{
    public int BookId { get; set; }

    public int? UserId { get; set; }

    public string BookName { get; set; }

    public string BookPrice { get; set; }

    public virtual User User { get; set; }
}