// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Lab.Accounting.API.Models;

public partial class AccountPracticeContext : DbContext
{
    public AccountPracticeContext(DbContextOptions<AccountPracticeContext> options)
        : base(options)
    {
    }

    public virtual DbSet<LedgerItem> LedgerItems { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LedgerItem>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK_AccountItem");

            entity.ToTable("LedgerItem");

            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Cost).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.ItemName)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("User");

            entity.Property(e => e.UserAccount)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UserName).HasMaxLength(200);
            entity.Property(e => e.UserPassword)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UserPhone).HasMaxLength(200);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}