// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab.Accounting.API.Models;

public partial class LedgerItem
{
    public int AccountId { get; set; }

    public string ItemName { get; set; }

    public string Category { get; set; }

    public decimal Cost { get; set; }

    public DateOnly? Date { get; set; }

    public string Illustrate { get; set; }
}