// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Lab.Accounting.API.Models;

public partial class User
{
    public int UserId { get; set; }

    public int UserLedger { get; set; }

    public string UserAccount { get; set; }

    public string UserPassword { get; set; }

    public string UserName { get; set; }

    public string UserPhone { get; set; }
}